server:
  port: 5053
spring:
  application:
    name: dfpm-prestamo-service

  datasource:
    url: jdbc:postgresql://ep-bold-fire-acpd4v3x-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_qIV6KStL0wBn&sslmode=require
    username: neondb_owner
    password: npg_qIV6KStL0wBn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5050/eureka
  instance:
    hostname: localhost
